### ISSUE TITLE
Proxy support, is it well documented?

### ISSUE THREAD

**Issue by earroyoron** [jetty-project/jetty-documentation#55]
I  am not able to use a proxy with HTTPS over HTTP (with a connect) as described in documentation, I always has an exception

Is this well documented? Am i doing anything wrong?
 
 		SslContextFactory sslContextFactory = new SslContextFactory();
        sslContextFactory.setTrustAll(Boolean.TRUE);
        sslContextFactory.setEndpointIdentificationAlgorithm(null);
        httpclient = new HttpClient(sslContextFactory);
        httpclient.setFollowRedirects(false);
        httpclient.setConnectTimeout(45000);
        ProxyConfiguration proxyConfig = httpclient.getProxyConfiguration();
        proxyConfig.getProxies().add( new HttpProxy("myproxy.somewhere.com",7011) );
        httpclient.start();
        ...
        ...
          ContentResponse response;
            response = httpclient.newRequest("https://somesite.com")
                    .method(HttpMethod.GET).send();

        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (TimeoutException e) {
            e.printStackTrace();
        }

        And I have this

        java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:639)
	at com.eurobits.agregador.comun.http.HttpJettyRequest.requestURI(HttpJettyRequest.java:145)
	at com.eurobits.agregador.particulares.bancos.caixa.CaixaLogin.login(CaixaLogin.java:129)
	at com.eurobits.agregador.particulares.bancos.caixa.CaixaLogin.tryLogin(CaixaLogin.java:97)
	at com.eurobits.agregador.comun.Login.doLogin(Login.java:128)
	at com.eurobits.agregador.particulares.ParticularesParserCard.firstPhase(ParticularesParserCard.java:290)
	at com.eurobits.agregador.particulares.ParticularesParserCard.buildXMLStandarExecute(ParticularesParserCard.java:253)
	at com.eurobits.agregador.particulares.ParticularesParserCard.buildXML(ParticularesParserCard.java:228)
	at com.eurobits.agregador.comun.Parser.getOutput(Parser.java:974)
	at com.eurobits.agregador.comun.BusinessFacadeImpl.execute(BusinessFacadeImpl.java:34)
	at com.eurobits.agregador.RobotTest.execute(RobotTest.java:439)
	at com.eurobits.agregador.RobotTest.testExecute(RobotTest.java:460)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:782)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:337)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:128)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:108)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:190)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:54)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:182)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:70)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:36)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:26)
	at org.eclipse.jetty.client.PoolingHttpDestination$2.run(PoolingHttpDestination.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 14 more

**Comment by luuuis** [comment]
I get the same error on Jetty 9.3.2.v20150730 (stable). My setup is:

* Using ProxyServlet.Transparent
* Using a `new HttpClient(new SslContextFactory)` that is configured to talk to a Squid proxy

Exception:

    2015-08-21 13:07:36:303 +1000 [qtp8437736-11] DEBUG 7f7052 - 2044261 proxying failed
    org.eclipse.jetty.io.EofException
      at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:200)
      at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:808)
      at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
      at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
      at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:135)
      at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:110)
      at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204)
      at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:78)
      at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:208)
      at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:81)
      at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:36)
      at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:26)
      at org.eclipse.jetty.client.PoolingHttpDestination.process(PoolingHttpDestination.java:122)
      at org.eclipse.jetty.client.PoolingHttpDestination.send(PoolingHttpDestination.java:71)
      at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:187)
      at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:533)
      at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:694)
      at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:678)
      at org.eclipse.jetty.proxy.AbstractProxyServlet.sendProxyRequest(AbstractProxyServlet.java:539)
      at org.eclipse.jetty.proxy.ProxyServlet.service(ProxyServlet.java:88)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
      at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1684)
      at com.atlassian.shipit32.ProxyPush$PushViewIssueFilter.doFilter(ProxyPush.scala:197)
      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
      at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
      at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:384)
      at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
      at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
      at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
      at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
      at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
      at org.eclipse.jetty.server.Server.handle(Server.java:517)
      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
      at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:261)
      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
      at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:96)
      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
      at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
      at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
      at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
      at java.lang.Thread.run(Thread.java:745)
    Caused by: java.nio.channels.ClosedChannelException
      at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:269)
      at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:460)
      at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:178)
      ... 51 more

**Comment by walaniam** [comment]
Has anyone resolved it? I'm having similar issue.

**Comment by earroyoron** [comment]
I have given up using this library

**Comment by luuuis** [comment]
I reported this as https://bugs.eclipse.org/bugs/show_bug.cgi?id=475546 and it was  fixed after just a few days. I haven't had a chance to test the fix myself.

**Comment by joakime** [comment]
@earroyoron why did you file a bug about jetty on its documentation site?  

This would have been far more appropriate on ...

 * The jetty-users mailing list (for casual help on issues setting up Jetty)
 * The Jetty bugzilla pages (for formal bugs on Jetty)
 * The Jetty tag on stackoverflow (for help setting up / configuring / using / troubleshooting the Jetty distribution)
 * The embedded-jetty tag on stackoverflow (for help setting up / configuring / troubleshooting when using Jetty in embedded mode)

This issue is like reporting a problematic engine that leaks oil to the Advertising company for the tires on your car.
